[package]
name = "libmdbx"
version = "0.1.1"
authors = [
  "Dan Burkert <dan@danburkert.com>",
  "Victor Porof <vporof@mozilla.com>",
  "Artem Vorotnikov <artem@vorotnikov.me>",
]
edition = "2021"
license = "Apache-2.0"
description = "Idiomatic and safe MDBX wrapper."
documentation = "https://docs.rs/libmdbx"
homepage = "https://github.com/vorot93/libmdbx-rs"
repository = "https://github.com/vorot93/libmdbx-rs"
readme = "README.md"
keywords = ["LMDB", "MDBX", "database", "storage-engine", "bindings"]
categories = ["database"]

[lib]
name = "libmdbx"

[workspace]
members = ["mdbx-sys"]

[dependencies]
bitflags = "1"
byteorder = "1"
derive_more = "0.99"
indexmap = "1"
libc = "0.2"
parking_lot = "0.11"
thiserror = "1"

ffi = { package = "mdbx-sys", version = "0.11.4-git.20210105", default-features = false, path = "./mdbx-sys" }

lifetimed-bytes = { version = "0.1", optional = true }

[features]
cmake = ["ffi/cmake-build"]
default = ["ffi/default"]
static = ["ffi/static"]

[dev-dependencies]
criterion = "0.3"
rand = "0.8"
rand_xorshift = "0.3"
tempfile = "3"

[[bench]]
name = "cursor"
harness = false

[[bench]]
name = "transaction"
harness = false
